### ISSUE TITLE
Instructions to Build

### ISSUE THREAD

**Issue by adilbaig** [mcleary/VulkanHpp-Compute-Sample#1]
Hi,

Could you add some instructions on how to build and run the example program on Linux. Here's what happens when I run this on my machine:

```bash
$ git clone git@github.com:mcleary/VulkanHpp-Compute-Sample.git
...
Resolving deltas: 100% (9/9), done.
$ cd VulkanHpp-Compute-Sample/
$ cmake -S . -B build
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adil/workspace/VulkanHpp-Compute-Sample/build
$ cd build/
$ make
Scanning dependencies of target ComputeShader
[ 33%] Buiding Shaders
/bin/sh: 1: /Bin/dxc: not found
make[2]: *** [CMakeFiles/ComputeShader.dir/build.make:80: Square.spv] Error 127
make[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/ComputeShader.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
$ 
```

**Comment by mcleary** [comment]
You just need to make sure you have dxc installed. Try running `which dxc` to see if you have it available. If you do, make sure the environment variable VK_SDK_PATH is pointing to the correct folder. If you have dxc in another folder you just need to adapt the CMakeLists.txt to make sure cmake can find it.

**Comment by NazimAliev** [comment]
> You just need to make sure you have dxc installed. Try running `which dxc` to see if you have it available. If you do, make sure the environment variable VK_SDK_PATH is pointing to the correct folder. If you have dxc in another folder you just need to adapt the CMakeLists.txt to make sure cmake can find it.

In case Vulkan SDK is installed from the packages (Ubuntu), dxc is placed on default path: /usr/bin/dxc
